
[functions.merge-pdf]
verify_jwt = false

[functions.create-asaas-charge]
verify_jwt = false

[functions.update-asaas-charge]
verify_jwt = false

[functions.cancel-asaas-charge]
verify_jwt = false

[functions.manage-asaas-customer]
verify_jwt = false

[functions.parse-invoice]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.transfer-asaas-pix]
verify_jwt = false

[functions.trigger-faturista]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.pay-asaas-bill]
verify_jwt = true
